export interface ProjectCapabilityDefinition {
	id: string;
	label: string;
	description: string;
	tags: string[];
	keywords: string[];
	categories?: string[];
	impactDomains?: string[];
	problemMappings?: string[];
}

export const projectCapabilities: ProjectCapabilityDefinition[] = [
	{
		id: "computer-vision",
		label: "Computer Vision",
		description: "Image, video, inspection, detection and tracking systems.",
		tags: [
			"Computer Vision",
			"YOLO",
			"Object Detection",
			"Object Tracking",
			"OCR",
			"Image Processing",
			"Video Analytics",
			"OpenCV",
		],
		keywords: [
			"computer vision",
			"object detection",
			"image inspection",
			"video analysis",
			"visual inspection",
			"yolo",
			"opencv",
		],
		impactDomains: ["Computer Vision and Perception"],
		problemMappings: ["computer-vision"],
	},
	{
		id: "generative-ai",
		label: "Generative AI",
		description: "Generative and foundation-model systems for content, reasoning and assistance.",
		tags: [
			"Generative AI",
			"GenAI",
			"LLM",
			"LLM Inference",
			"Local LLM",
			"Gemini",
			"GPT-4o-mini",
			"Ollama",
		],
		keywords: [
			"generative ai",
			"large language model",
			"foundation model",
			"llm inference",
			"local llm",
			"ollama",
		],
		impactDomains: ["Generative AI and Foundation Models"],
		problemMappings: ["generative-ai"],
	},
	{
		id: "agentic-ai",
		label: "Agentic AI",
		description: "Goal-directed agents, planning systems and tool-orchestration workflows.",
		tags: [
			"Agentic AI",
			"AI Agent",
			"Agents",
			"LLM Agents",
			"MCP",
			"Orchestration",
		],
		keywords: [
			"agentic ai",
			"ai agent",
			"llm agent",
			"multi-agent",
			"autonomous agent",
			"agent orchestration",
			"mcp control plane",
		],
		impactDomains: ["Agentic AI and Automation"],
	},
	{
		id: "mlops",
		label: "MLOps",
		description: "Repeatable model delivery, validation, monitoring and operational workflows.",
		tags: [
			"MLOps",
			"Model Monitoring",
			"ML Pipeline",
			"Model Deployment",
			"CI/CD",
		],
		keywords: [
			"mlops",
			"model pipeline",
			"model monitoring",
			"model deployment",
			"inference pipeline",
			"reproducible training",
		],
		impactDomains: ["AI Platforms and MLOps"],
	},
	{
		id: "snowflake",
		label: "Snowflake",
		description: "Snowflake-backed data, analytics and governed warehouse solutions.",
		tags: ["Snowflake", "Snowpark", "Snowflake Cortex"],
		keywords: [
			"snowflake",
			"snowpark",
			"snowflake cortex",
			"snowflake-ready",
		],
	},
	{
		id: "edge-deployment",
		label: "Edge Deployment",
		description: "On-device, local or resource-constrained model deployment.",
		tags: [
			"Edge Deployment",
			"Edge AI",
			"On-Device AI",
			"In-Vehicle AI",
		],
		keywords: [
			"edge deployment",
			"edge ai",
			"on-device",
			"in-vehicle inference",
			"resource-constrained inference",
		],
	},
	{
		id: "cloud-deployment",
		label: "Cloud Deployment",
		description: "Cloud-hosted applications, APIs and model-serving environments.",
		tags: [
			"Cloud Deployment",
			"Azure",
			"Azure Container Apps",
			"Azure Functions",
			"Hugging Face",
			"Hugging Face Spaces",
			"Docker",
		],
		keywords: [
			"cloud deployment",
			"azure container apps",
			"azure functions",
			"hugging face space",
			"container deployment",
			"cloud-hosted",
		],
		impactDomains: ["AI Platforms and MLOps"],
	},
	{
		id: "explainability",
		label: "Explainability",
		description: "Traceable outputs, reasons, evidence and human-review support.",
		tags: [
			"Explainability",
			"Explainable AI",
			"Evidence Pack",
			"Audit Trail",
			"Human-in-the-Loop",
		],
		keywords: [
			"explainable",
			"explainability",
			"evidence-grounded",
			"reason code",
			"audit trail",
			"traceable decision",
		],
	},
	{
		id: "document-intelligence",
		label: "Document Intelligence",
		description: "OCR, document parsing, extraction and evidence reconciliation.",
		tags: [
			"Document Intelligence",
			"OCR",
			"Document AI",
			"Document Processing",
			"Information Extraction",
		],
		keywords: [
			"document intelligence",
			"document processing",
			"document extraction",
			"ocr workflow",
			"text extraction",
			"pdf parsing",
		],
		problemMappings: ["healthcare"],
	},
	{
		id: "predictive-analytics",
		label: "Predictive Analytics",
		description: "Forecasting, failure-risk, scoring and forward-looking analytics.",
		tags: [
			"Predictive Analytics",
			"Predictive Maintenance",
			"Failure Prediction",
			"Risk Monitoring",
			"Forecasting",
		],
		keywords: [
			"predictive analytics",
			"failure risk",
			"risk forecast",
			"forecasting",
			"prediction model",
			"predictive maintenance",
		],
		impactDomains: ["Industrial Intelligence"],
		problemMappings: ["predictive-maintenance"],
	},
	{
		id: "optimization",
		label: "Optimization",
		description: "Constraint, routing and resource-allocation optimization systems.",
		tags: [
			"Optimization",
			"VRP",
			"Vehicle Routing",
			"OR-Tools",
			"PyVRP",
			"Route Optimization",
		],
		keywords: [
			"optimization",
			"vehicle routing problem",
			"route optimization",
			"or-tools",
			"pyvrp",
			"constraint solver",
		],
		impactDomains: ["Optimization and Logistics"],
		problemMappings: ["logistics"],
	},
	{
		id: "security",
		label: "Security",
		description: "Security automation, identity, privacy and trust controls.",
		tags: [
			"Security",
			"DevSecOps",
			"Zero-Knowledge Proofs",
			"Decentralized Identity",
			"Privacy-Preserving Identity",
			"Selective Disclosure",
		],
		keywords: [
			"devsecops",
			"security gate",
			"zero-knowledge proof",
			"decentralized identity",
			"privacy-preserving",
			"selective disclosure",
		],
		impactDomains: ["Security, Identity and Trust"],
		problemMappings: ["security"],
	},
	{
		id: "multimodal-ai",
		label: "Multimodal AI",
		description: "Systems that combine text, image, audio, video or other modalities.",
		tags: [
			"Multimodal AI",
			"Vision-Language Model",
			"Voice AI",
			"Digital Human",
			"Qwen2.5-VL",
		],
		keywords: [
			"multimodal ai",
			"vision-language model",
			"vision language model",
			"text and image",
			"voice generation",
			"digital human",
		],
	},
	{
		id: "workflow-automation",
		label: "Workflow Automation",
		description: "Automated multi-step business and technical workflows.",
		tags: [
			"Workflow Automation",
			"Orchestration",
			"Process Automation",
			"Automation",
			"Microservices",
		],
		keywords: [
			"workflow automation",
			"process automation",
			"workflow orchestration",
			"automated workflow",
			"multi-step workflow",
		],
		impactDomains: ["Agentic AI and Automation"],
	},
	{
		id: "data-analytics",
		label: "Data Analytics",
		description: "Data modelling, dashboards, measurement and decision analytics.",
		tags: [
			"Data Analytics",
			"Analytics",
			"Financial Analytics",
			"Data Visualization",
			"Plotly",
			"pandas",
		],
		keywords: [
			"data analytics",
			"analytics dashboard",
			"financial analytics",
			"data visualization",
			"analytical view",
			"decision analytics",
		],
		impactDomains: ["Industrial Intelligence"],
	},
];
